const text = [
	`Praxis flexitarian artisan farm-to-table snackwave typewriter cliche readymade bespoke taiyaki health goth mlkshk DSA. Williamsburg brunch ramps pickled pok pok skateboard gatekeep salvia cardigan praxis. Occupy etsy palo santo artisan. Chartreuse DSA messenger bag shoreditch tilde pitchfork.`,

	`Green juice quinoa air plant jianbing, YOLO cloud bread PBR&B vinyl. Slow-carb bitters semiotics vibecession, yr mlkshk skateboard literally kogi roof party 3 wolf moon big mood art party. Squid four dollar toast aesthetic la croix, knausgaard green juice poke trust fund deep v whatever. Disrupt man braid kitsch, dreamcatcher tousled authentic typewriter locavore DIY pinterest artisan messenger bag.`,

	`Cornhole normcore big mood intelligentsia blackbird spyplane kogi. Chambray bodega boys blue bottle, asymmetrical you probably haven't heard of them XOXO twee paleo knausgaard synth kitsch cold-pressed viral Brooklyn wayfarers. Schlitz sus activated charcoal cloud bread wayfarers XOXO williamsburg 90's hexagon tacos typewriter twee. Live-edge sartorial try-hard, tote bag vibecession franzen keytar. Drinking vinegar polaroid bicycle rights vibecession actually ennui salvia, literally taiyaki master cleanse beard.`,

	`Actually fingerstache next level snackwave bitters post-ironic authentic JOMO squid asymmetrical try-hard yr deep v man braid vibecession. Vaporware food truck unicorn narwhal actually aesthetic gochujang hell of +1 cray. Kombucha readymade put a bird on it, pinterest DSA bitters cardigan synth pok pok. Distillery poke portland retro. Whatever try-hard keytar coloring book cupping roof party.`,

	`Swag keffiyeh normcore humblebrag small batch. Shoreditch quinoa locavore jean shorts unicorn knausgaard coloring book 8-bit try-hard yr godard. Sus blog whatever pug, shoreditch shabby chic iPhone jianbing coloring book man bun. Tbh sustainable pork belly microdosing typewriter cloud bread. Ugh squid tacos, next level portland shaman pinterest narwhal man bun selfies. Shoreditch hella 3 wolf moon echo park.`,

	`Tofu raclette wayfarers, af vinyl put a bird on it food truck salvia copper mug migas literally everyday carry authentic enamel pin taiyaki. Hexagon man braid semiotics, dreamcatcher hammock neutral milk hotel salvia quinoa banjo poutine kinfolk edison bulb readymade pabst vibecession. Shaman shabby chic cornhole tumblr offal tote bag tumeric. Franzen gentrify DIY aesthetic solarpunk 3 wolf moon kombucha before they sold out tumeric praxis cred air plant DSA artisan. Fanny pack selvage scenester kickstarter aesthetic.`,

	`Readymade lomo flexitarian farm-to-table edison bulb celiac sriracha single-origin coffee four dollar toast biodiesel street art kitsch dreamcatcher aesthetic blackbird spyplane. Vibecession raw denim cloud bread, roof party authentic shaman post-ironic JOMO live-edge gastropub ramps franzen next level cray crucifix. Banjo copper mug four loko coloring book freegan cronut yr kombucha. Shoreditch keffiyeh flexitarian you probably haven't heard of them gatekeep next level.`,

	`Butcher 8-bit letterpress meditation vice. Keffiyeh hell of live-edge franzen chillwave. Plaid kogi gluten-free, shaman snackwave selvage paleo same cardigan taxidermy green juice. Kickstarter marxism shaman pickled authentic, raclette tofu tumeric put a bird on it cred. Quinoa keytar kinfolk truffaut, microdosing 3 wolf moon literally bodega boys tbh enamel pin ramps. Irony echo park wayfarers, kinfolk woke lumbersexual tonx offal bushwick etsy tote bag jianbing asymmetrical aesthetic sriracha. 90's blackbird spyplane gastropub lumbersexual freegan heirloom, bespoke fashion axe prism keffiyeh.`,

	`Truffaut mukbang JOMO chicharrones kombucha gluten-free marxism 8-bit occupy pok pok everyday carry kinfolk microdosing. Vexillologist echo park blog hammock kickstarter af marfa listicle mlkshk. Single-origin coffee synth DSA selfies bruh pitchfork. Unicorn edison bulb twee kickstarter messenger bag squid vaporware waistcoat, small batch ethical. 90's shoreditch normcore, kitsch raclette woke slow-carb pok pok fam try-hard fit wolf salvia. Neutra la croix jawn cornhole fanny pack hexagon hot chicken direct trade bicycle rights, selfies mukbang keffiyeh banh mi pop-up.`,

	`Cupping try-hard yes plz, iceland gastropub yr pinterest intelligentsia. Man braid chillwave yes plz church-key. Health goth nostrud mlkshk skateboard in tempor narwhal eu ethical letterpress. Godard dolore literally 90's. Humblebrag +1 everyday carry pour-over in.`,
];

export default text;